
mongodb:
  service:
    type: NodePort
    nodePort: 30268

activemq:
  service:
    type: NodePort
    http:
      enabled: true
      nodePort: 30269
    core:
      enabled: true
      nodePort: 30270

webBack:
  service:
    type: NodePort
    httpNodePort: 30267