apiVersion: v1
kind: ConfigMap
metadata:
  name: {{include "nodejs-entrypoint.name" . }}
data:
  entrypoint.sh: |-
    #
    node ./server.js 2>&1 | tee {{.Values.deployment.nodeJsApps.containerLogFolder}}/output.log
    #
